services:
  metamodels.attribute_tablemulti.factory:
    class: MetaModels\AttributeTableMultiBundle\Attribute\AttributeTypeFactory
    arguments:
      - '@database_connection'
      - '@=service("contao.framework").getAdapter("Contao\\StringUtil")'
      - '@=service("contao.framework").getAdapter("Contao\\Validator")'
    tags:
      - { name: metamodels.attribute_factory }

  MetaModels\AttributeTableMultiBundle\Migration\ChangeTableNameMigration:
    arguments:
      - '@database_connection'
    tags:
      - name: contao.migration
