services:
    metamodels.attribute_tabletext.factory:
        class: MetaModels\Attribute\TableText\AttributeTypeFactory
        arguments:
            - '@database_connection'
        tags:
          - { name: metamodels.attribute_factory }
